# Generated by Django 2.2.1 on 2019-05-07 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='address',
            new_name='kingdom',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='country',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='username',
        ),
    ]
