# Generated by Django 2.2.1 on 2019-05-09 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190509_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zip',
            name='Zip',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
