# Generated by Django 2.2.1 on 2019-05-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190510_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='house_number',
            field=models.IntegerField(max_length=255),
        ),
    ]
