# Generated by Django 2.2.1 on 2019-05-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20190510_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='house_number',
            field=models.IntegerField(),
        ),
    ]
