# Generated by Django 2.2.1 on 2019-05-10 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_buyer_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='house_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='postcode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Postcode'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='ssn',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='profile_image',
            field=models.CharField(blank=True, max_length=9999, null=True),
        ),
    ]
