# Generated by Django 2.2.1 on 2019-05-12 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20190510_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='house_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ssn',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='street',
        ),
        migrations.DeleteModel(
            name='Buyer',
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
