# Generated by Django 2.2.1 on 2019-05-12 21:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_searchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='time_stamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
