# Generated by Django 2.2.1 on 2019-05-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_auto_20190507_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='info',
            field=models.TextField(default='placeholdertext'),
            preserve_default=False,
        ),
    ]
