# Generated by Django 2.2.1 on 2019-05-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotVerified',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('zip', models.IntegerField()),
                ('price', models.IntegerField()),
                ('commission', models.IntegerField()),
                ('rooms', models.IntegerField()),
                ('verified', models.BooleanField()),
                ('info', models.TextField()),
            ],
            options={
                'db_table': 'not_verified',
                'managed': False,
            },
        ),
    ]
