# Generated by Django 2.2.1 on 2019-05-08 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_notverified'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotVerified',
        ),
    ]
