# Generated by Django 2.2.1 on 2019-05-09 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_notverified'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotVerified',
        ),
        migrations.RemoveField(
            model_name='property',
            name='userinfo_id',
        ),
    ]
