# Generated by Django 2.2.1 on 2019-05-10 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0007_auto_20190509_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Castle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('zip', models.IntegerField()),
                ('price', models.IntegerField()),
                ('commission', models.IntegerField()),
                ('rooms', models.IntegerField()),
                ('size', models.IntegerField()),
                ('verified', models.BooleanField()),
                ('info', models.TextField()),
                ('street', models.CharField(max_length=255)),
                ('house_number', models.IntegerField()),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CastleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=999)),
                ('castle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.Castle')),
            ],
        ),
    ]
