# Generated by Django 2.2.1 on 2019-05-10 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_castle_castleimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='castle',
            old_name='zip',
            new_name='postcode',
        ),
    ]
