# Generated by Django 2.2.1 on 2019-05-10 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_auto_20190510_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='castle',
            name='postcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Postcode'),
        ),
    ]
