# Generated by Django 2.2.1 on 2019-05-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_castleoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='castleoffer',
            name='info',
            field=models.TextField(default='no info'),
            preserve_default=False,
        ),
    ]
