# Generated by Django 2.2.1 on 2019-05-14 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0015_contactinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldCastle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('commission', models.IntegerField()),
                ('rooms', models.IntegerField()),
                ('size', models.IntegerField()),
                ('info', models.TextField()),
                ('street', models.CharField(max_length=255)),
                ('house_number', models.IntegerField()),
                ('time_stamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('postcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Postcode')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
