# Generated by Django 2.2.1 on 2019-05-14 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0016_soldcastle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldcastle',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soldcastle_requests_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
