# Generated by Django 2.2.1 on 2019-05-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0018_auto_20190514_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='ssn',
            field=models.BigIntegerField(),
        ),
    ]
